name: Debug Dispatch Events

on:
  repository_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "✅ Event received!"
          echo "Event name: ${{ github.event.action }}"
          echo "Event type: ${{ github.event.client_payload.technology }}"
          echo "Full payload:"
          echo "${{ toJSON(github.event) }}"
