name: Remote Code Scan

on:
  repository_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Print event info
        run: |
          echo "Event Type: ${{ github.event.action }}"
          echo "Payload:"
          echo '${{ toJson(github.event.client_payload) }}'